# Generated by Django 4.1.3 on 2022-12-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='film_img/')),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
