# Generated by Django 4.1.3 on 2022-12-07 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_delete_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Films',
        ),
    ]
