# Generated by Django 4.1.3 on 2022-12-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_film_created_alter_film_img_film_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='img',
            field=models.ImageField(upload_to='films/'),
        ),
    ]
